version: '3'

services:
  app:
    tty: true
    build: .
    image: barber:latest
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true